export const AMBER = '#f5a623';

export const productSections = [
  {
    id: 'most-sold', title: 'Most Sold', subtitle: 'Top-selling products across all categories.', accentColor: AMBER,
    products: [
      { id: '1',  name: 'HC-SR04 Ultra Sonic Sensor',                   price: '5',   dec: '00', stock: 'In Stock',    low: false },
      { id: '2',  name: 'Arduino Uno R3 SMD CH340 Clone',               price: '18',  dec: '00', stock: 'In Stock',    low: false },
      { id: '3',  name: 'Arduino IR Receiver - Transmitter Module',      price: '6',   dec: '00', stock: 'In Stock',    low: false },
      { id: '4',  name: 'MG996 Metal Servo Motor',                       price: '12',  dec: '00', stock: 'In Stock',    low: false },
      { id: '5',  name: 'Large Breadboard 830',                          price: '8',   dec: '00', stock: 'In Stock',    low: false },
      { id: '6',  name: 'L298 DC Motor Driver Module',                   price: '8',   dec: '00', stock: 'In Stock',    low: false },
      { id: '7',  name: 'Mini Breadboard',                               price: '3',   dec: '00', stock: 'In Stock',    low: false },
      { id: '8',  name: 'Arduino Buzzer Board / Module',                 price: '3',   dec: '00', stock: 'In Stock',    low: false },
      { id: '9',  name: 'ESP32-WROOM-32D Wifi Bluetooth Module',         price: '24',  dec: '00', stock: 'In Stock',    low: false },
      { id: '10', name: 'JUMPER WIRES Set (M-M / F-F / M-F)',           price: '0',   dec: '14', stock: 'In Stock',    low: false },
    ],
  },
  {
    id: 'arduino', title: 'Arduino', subtitle: 'Boards, modules and sensors for every project.', accentColor: '#00979d',
    products: [
      { id: '1',  name: 'Arduino Uno R3 SMD CH340 Clone',               price: '18',  dec: '00', stock: 'In Stock',    low: false },
      { id: '2',  name: 'Arduino MEGA 2560 R3 Clone CH340',             price: '28',  dec: '00', stock: 'Only 3 left', low: true  },
      { id: '3',  name: 'Arduino Nano Clone - USB CH340',               price: '16',  dec: '00', stock: 'In Stock',    low: false },
      { id: '4',  name: 'ESP32-WROOM-32D Wifi Bluetooth Module',        price: '24',  dec: '00', stock: 'In Stock',    low: false },
      { id: '5',  name: 'ESP32 S3 N16R8',                               price: '30',  dec: '00', stock: 'In Stock',    low: false },
      { id: '6',  name: 'ESP32-S3 ZERO Development Board',              price: '20',  dec: '00', stock: 'Only 3 left', low: true  },
      { id: '7',  name: 'V3 NodeMcu CH-340 WiFi Module ESP8266',        price: '18',  dec: '00', stock: 'Only 2 left', low: true  },
      { id: '8',  name: 'Raspberry Pi 4 2GB - Model B',                 price: '141', dec: '00', stock: 'Only 1 left', low: true  },
      { id: '9',  name: 'Raspberry Pi Zero 2 W',                        price: '78',  dec: '00', stock: 'Only 1 left', low: true  },
      { id: '10', name: 'Raspberry Pi Zero W',                          price: '67',  dec: '00', stock: 'Only 1 left', low: true  },
      { id: '11', name: 'DHT11 Temperature & Humidity Sensor',          price: '6',   dec: '00', stock: 'In Stock',    low: false },
      { id: '12', name: 'DHT22 Temperature Sensor',                     price: '15',  dec: '00', stock: 'Only 1 left', low: true  },
      { id: '13', name: 'HC-SR04 Ultra Sonic Sensor',                   price: '5',   dec: '00', stock: 'In Stock',    low: false },
      { id: '14', name: 'PIR Motion Sensor Module',                     price: '5',   dec: '00', stock: 'In Stock',    low: false },
      { id: '15', name: 'RC522 RFID TAG READER 13.56 MHz',              price: '8',   dec: '00', stock: 'In Stock',    low: false },
      { id: '16', name: '16x2 LCD Display I2C Module',                  price: '12',  dec: '00', stock: 'In Stock',    low: false },
      { id: '17', name: '0.96" OLED Graphic LCD SSD1306 4 Pin',        price: '14',  dec: '00', stock: 'Only 2 left', low: true  },
      { id: '18', name: 'MG90S Servo Motor',                            price: '12',  dec: '00', stock: 'In Stock',    low: false },
      { id: '19', name: 'Tower Pro SG90 Micro Servo Motor',             price: '10',  dec: '00', stock: 'In Stock',    low: false },
      { id: '20', name: '4WD Wheel Robot Car Kit',                      price: '28',  dec: '00', stock: 'Only 2 left', low: true  },
    ],
  },
  {
    id: 'solar', title: 'Solar', subtitle: 'Solar panels, inverters and energy solutions.', accentColor: '#f5a623',
    products: [
      { id: '1',  name: 'TT MOBIL GUC ISTASYONU 1200W-1020WH PLUS',    price: '84818',dec: '00', stock: 'Only 2 left', low: true  },
      { id: '2',  name: '125W Foldable Solar Panel CW',                 price: '34578',dec: '00', stock: 'Only 1 left', low: true  },
      { id: '3',  name: 'DX APEX POWER',                               price: '160',  dec: '00', stock: 'Only 1 left', low: true  },
      { id: '4',  name: 'CN3791 MPPT Charge Controller 12V',           price: '11',   dec: '00', stock: 'Only 1 left', low: true  },
      { id: '5',  name: '6V Mini Solar Panel 105X66',                  price: '7',    dec: '00', stock: 'Only 1 left', low: true  },
      { id: '6',  name: 'ESP32-S3-N16R8-CAMERA',                       price: '35',   dec: '00', stock: 'Only 2 left', low: true  },
      { id: '7',  name: 'ARDUINO UNO STARTER SET',                     price: '35',   dec: '00', stock: 'Only 2 left', low: true  },
      { id: '8',  name: 'Lm2596 DC-DC Adjustable Step Down Module',    price: '4',    dec: '00', stock: 'In Stock',    low: false },
      { id: '9',  name: 'Step Down LM2596 DC-DC + Display',           price: '10',   dec: '00', stock: 'In Stock',    low: false },
      { id: '10', name: 'XL4015 5A Adjustable DC/DC Step Down',       price: '10',   dec: '00', stock: 'Only 1 left', low: true  },
    ],
  },
  {
    id: 'mexxsun', title: 'Mexxsun', subtitle: 'Renewable energy inverters and power systems.', accentColor: '#10b981',
    products: [
      { id: '1',  name: 'Mexxsun Inverter Charger Lithium 1',          price: '19397',dec: '00', stock: 'Only 2 left', low: true  },
      { id: '2',  name: 'Mexxsun Inverter Charger Lithium 2',          price: '22491',dec: '00', stock: 'Only 2 left', low: true  },
      { id: '3',  name: 'Mexxsun Inverter Charger Lithium 3',          price: '26894',dec: '00', stock: 'Only 2 left', low: true  },
      { id: '4',  name: 'Mexxsun Inverter Charger Lithium 4',          price: '38794',dec: '00', stock: 'Only 2 left', low: true  },
      { id: '5',  name: 'Mexxsun Power System 27540W',                 price: '27540',dec: '00', stock: 'Only 2 left', low: true  },
      { id: '6',  name: 'Mexxsun Power System 43860W',                 price: '43860',dec: '00', stock: 'Only 2 left', low: true  },
      { id: '7',  name: 'Mexxsun Power System 52530W',                 price: '52530',dec: '00', stock: 'Only 2 left', low: true  },
      { id: '8',  name: 'Mexxsun Power System 46291W',                 price: '46291',dec: '00', stock: 'Only 1 left', low: true  },
      { id: '9',  name: 'Mexxsun Accessory 663W',                      price: '663',  dec: '00', stock: 'In Stock',    low: false },
      { id: '10', name: 'Mexxsun Panel Kit 7140W',                     price: '7140', dec: '00', stock: 'In Stock',    low: false },
    ],
  },
  {
    id: 'fans', title: 'Fans', subtitle: 'Cooling fans and ventilation systems.', accentColor: '#06b6d4',
    products: [
      { id: '1',  name: 'MARXLOW 40 x 40 x 10mm 12V',                 price: '4',   dec: '00', stock: 'In Stock',    low: false },
      { id: '2',  name: '5 x 5 FAN INCE',                              price: '5',   dec: '00', stock: 'In Stock',    low: false },
      { id: '3',  name: '120 x 120 x 25mm 12V Fan',                   price: '5',   dec: '00', stock: 'In Stock',    low: false },
      { id: '4',  name: '120 X 120 X 25mm 24V Fan',                   price: '12',  dec: '00', stock: 'Only 2 left', low: true  },
      { id: '5',  name: '90 x 90 x 25mm 9x9 12V Fan',                 price: '4',   dec: '00', stock: 'In Stock',    low: false },
      { id: '6',  name: 'MARXLOW 80 x 80 x 25mm 12V',                 price: '4',   dec: '00', stock: 'In Stock',    low: false },
      { id: '7',  name: '70 x 70 x 15mm Boxed Case Fan',              price: '10',  dec: '00', stock: 'In Stock',    low: false },
      { id: '8',  name: '60 x 60 x 15mm 12V Case Fan',                price: '3',   dec: '00', stock: 'In Stock',    low: false },
      { id: '9',  name: 'FAN 60 X 60 X 25 12V DC 3 Cable',            price: '4',   dec: '00', stock: 'Only 1 left', low: true  },
      { id: '10', name: 'Raspberry Pi CPU Fan',                        price: '5',   dec: '00', stock: 'In Stock',    low: false },
    ],
  },
  {
    id: 'batteries', title: 'Batteries', subtitle: 'Rechargeable batteries and power storage.', accentColor: '#e3342f',
    products: [
      { id: '1',  name: '18500 ORION Rechargeable Li-Ion Battery',     price: '6',   dec: '00', stock: 'Only 3 left', low: true  },
      { id: '2',  name: 'SUPEX NI-CD SP2000SC-2Y',                    price: '10',  dec: '00', stock: 'Only 3 left', low: true  },
      { id: '3',  name: 'GP GREENCELL EXTRA HEAVY DUTY',               price: '4',   dec: '00', stock: 'Only 3 left', low: true  },
      { id: '4',  name: 'YOKOHAMA BATTERIES 12V 5A',                  price: '20',  dec: '00', stock: 'Only 2 left', low: true  },
      { id: '5',  name: 'MAX PERFORMANCE GOLD 12V 1.3A',              price: '15',  dec: '00', stock: 'Only 1 left', low: true  },
      { id: '6',  name: 'TTEC 6V 4AH/20HR BATTERY',                   price: '13',  dec: '00', stock: 'Only 1 left', low: true  },
      { id: '7',  name: 'VARTA SUPER HEAVY DUTY',                     price: '9',   dec: '00', stock: 'Only 1 left', low: true  },
      { id: '8',  name: 'BATMAX 102030 600mAh',                       price: '12',  dec: '00', stock: 'Only 1 left', low: true  },
      { id: '9',  name: 'ORION 1000MAH AA',                           price: '4',   dec: '00', stock: 'Only 1 left', low: true  },
      { id: '10', name: 'XTAR MC1 Type-C Li-Ion Battery Charger',     price: '10',  dec: '00', stock: 'Only 1 left', low: true  },
    ],
  },
  {
    id: 'adapters', title: 'Adapters', subtitle: 'Power adapters and converters for everyday electronics.', accentColor: '#3b82f6',
    products: [
      { id: '1',  name: '5V 2A WEKO Wall-Mounted Adapter',            price: '10',  dec: '00', stock: 'Only 2 left', low: true  },
      { id: '2',  name: '12V 2A ADAPTER',                             price: '12',  dec: '00', stock: 'Only 1 left', low: true  },
      { id: '3',  name: '12V 2.5A ADAPTOR WHITE',                     price: '14',  dec: '00', stock: 'Only 1 left', low: true  },
      { id: '4',  name: '6V 1.67A ADAPTOR',                           price: '7',   dec: '00', stock: 'Only 1 left', low: true  },
      { id: '5',  name: '9V 2.5A Adaptor',                            price: '464', dec: '89', stock: 'In Stock',    low: false },
      { id: '6',  name: '9V 3A ADAPTOR',                              price: '418', dec: '40', stock: 'In Stock',    low: false },
      { id: '7',  name: '3.6V 1A Shaver Charger Adapter',            price: '348', dec: '67', stock: 'Only 1 left', low: true  },
      { id: '8',  name: '4.2V 0.6A Shaver Charger Adapter',          price: '348', dec: '67', stock: 'Only 2 left', low: true  },
      { id: '9',  name: '6V 0.12 Shaver Charger Adapter',            price: '348', dec: '67', stock: 'Only 3 left', low: true  },
      { id: '10', name: '20V 1A ADAPTOR WEKO',                        price: '464', dec: '89', stock: 'In Stock',    low: false },
    ],
  },
  {
    id: 'sound', title: 'Sound', subtitle: 'Speakers, mixers and audio systems.', accentColor: '#a855f7',
    products: [
      { id: '1',  name: 'WIRELESS KARAOKE SPEAKERS',                   price: '12',  dec: '00', stock: 'Only 1 left', low: true  },
      { id: '2',  name: 'PAM8403 2Ch 3W Mini Amplifier',              price: '7',   dec: '00', stock: 'Only 3 left', low: true  },
      { id: '3',  name: 'MAX98357 I2S CLASS D AMPLIFIER',              price: '7',   dec: '00', stock: 'Only 1 left', low: true  },
      { id: '4',  name: 'Arduino MP3 Player / Sound Module',           price: '7',   dec: '00', stock: 'Only 1 left', low: true  },
      { id: '5',  name: 'Sound Sensor Board Microphone 4 Pin',        price: '5',   dec: '00', stock: 'Only 1 left', low: true  },
      { id: '6',  name: 'Mems I2S Omnidirectional Microphone Module', price: '5',   dec: '00', stock: 'Only 1 left', low: true  },
      { id: '7',  name: '3.5mm Stereo to 2 RCA 1.5m Cable',          price: '5',   dec: '00', stock: 'Only 1 left', low: true  },
      { id: '8',  name: '1.5M Male to Male Stereo Aux Cable',         price: '5',   dec: '00', stock: 'Only 2 left', low: true  },
      { id: '9',  name: 'USB MIDI CABLE',                              price: '20',  dec: '00', stock: 'Only 1 left', low: true  },
      { id: '10', name: '3 Meter Guitar Jack Cable 2RCA+2Mono',       price: '10',  dec: '00', stock: 'Only 1 left', low: true  },
    ],
  },
  {
    id: 'filaments', title: 'Filaments', subtitle: '3D printing filaments — PLA, ABS, PETG & more.', accentColor: '#ec4899',
    products: [
      { id: '1',  name: 'ABS - Black',                                 price: '31',  dec: '00', stock: 'Only 1 left', low: true  },
      { id: '2',  name: 'ABS - Grey',                                  price: '31',  dec: '00', stock: 'Only 1 left', low: true  },
      { id: '3',  name: 'ABS - White/Cream',                          price: '31',  dec: '00', stock: 'Only 1 left', low: true  },
      { id: '4',  name: 'ABS - Yellow RAL',                           price: '34',  dec: '00', stock: 'Only 1 left', low: true  },
      { id: '5',  name: 'ABS - Green RAL',                            price: '34',  dec: '00', stock: 'Only 1 left', low: true  },
      { id: '6',  name: 'Silk PLA Dual Color Black & Red',            price: '35',  dec: '00', stock: 'Only 1 left', low: true  },
      { id: '7',  name: 'KUTEL 1.2MM 200g 60/40 TIN LEAD',           price: '22',  dec: '00', stock: 'Only 1 left', low: true  },
      { id: '8',  name: 'POWERMASTER LED STRIP DAYLIGHT 60 LEDs',     price: '6',   dec: '00', stock: 'Only 1 left', low: true  },
      { id: '9',  name: 'Resistor LED Capacitor Set',                  price: '8',   dec: '00', stock: 'Only 1 left', low: true  },
      { id: '10', name: '10 PCS 40 PIN Male-Male Pin Header',         price: '4',   dec: '00', stock: 'Only 3 left', low: true  },
    ],
  },
  {
    id: 'electronics', title: 'Electronics', subtitle: 'Cables, connectors and daily electronics.', accentColor: '#2ecc71',
    products: [
      { id: '1',  name: 'SHORT USB TYPE-C CABLE',                     price: '6',   dec: '00', stock: 'Only 3 left', low: true  },
      { id: '2',  name: 'HDMI to HDMI 1.5m Cable',                   price: '10',  dec: '00', stock: 'Only 1 left', low: true  },
      { id: '3',  name: 'HDTV Premium 2.0V 2M High Speed HDMI',      price: '12',  dec: '00', stock: 'Only 1 left', low: true  },
      { id: '4',  name: '1.5 Meter VGA Cable',                       price: '5',   dec: '00', stock: 'Only 1 left', low: true  },
      { id: '5',  name: 'C13 Power Cable / Monitor Cable',            price: '9',   dec: '00', stock: 'Only 3 left', low: true  },
      { id: '6',  name: '128GB SAN DISK Flash Drive',                 price: '10',  dec: '00', stock: 'Only 1 left', low: true  },
      { id: '7',  name: 'SeaGate 3 TB Hard Drive',                   price: '120', dec: '00', stock: 'Only 1 left', low: true  },
      { id: '8',  name: 'Everest Wireless Mouse',                     price: '10',  dec: '00', stock: 'Only 2 left', low: true  },
      { id: '9',  name: 'Ethernet RJ45 3-Way Distributor Splitter',  price: '9',   dec: '00', stock: 'Only 1 left', low: true  },
      { id: '10', name: '42V 2A Electric Scooter Charging Cable',    price: '5',   dec: '00', stock: 'Only 3 left', low: true  },
    ],
  },
];
